accounts/urls.py
from django.urls import path
from accounts import views

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
]

tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.TaskListView.as_view(), name='list'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('add-task/', views.add_task, name='api-add-task'),
    path('complete/<int:uid>', views.complete_task, name='complete'),
    path('delete/<int:uid>', views.delete_task, name='delete'),
    path('details/<int:pk>', views.TaskDetailView.as_view(), name='details'),
]
    

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('tasks/', include('tasks.urls', namespace="tasks")),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models


class TodoItem(models.Model):
    description = models.CharField(max_length=62)
    is_completed = models.BooleanField("выполнено", default=False)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.description.lower()

    class Meta:
        ordering = ('-created',)

accounts/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

tasks/forms.py
from ast import Pass
from dataclasses import field
from django import forms
from tasks.models import TodoItem

class AddTaskForm(forms.Form):
    description = forms.CharField(max_length=64, label='')

class TodoItemForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ('description',)
        labels = {"description": ""}


        

accounts/views.py
# -*- coding: UTF-8 -*-
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.views import View
from accounts.forms import LoginForm

class LoginView(View):
    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request,
                username=cd['username'],
                password=cd['password']
            )
            if user is None:
                return HttpResponse('Неправильный логин или пароль!')

            if not user.is_active:
                return HttpResponse('Ваш аккаунт заблокирован')

            login(request, user)
            return render(request, 'accounts/login.html', {'form': form})

    def get(self, request, *args, **kwargs):
        form = LoginForm()
        return render(request, 'accounts/login.html', {'form': form})

tasks/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.shortcuts import redirect
from django.views import View
from django.views.generic import ListView, DetailView
from tasks.forms import TodoItemForm
from tasks.models import TodoItem


def index(request):
    return HttpResponse("Примитивный ответ из приложения tasks")


def complete_task(request, uid):
    t = TodoItem.objects.get(id=uid)
    t.is_completed = True
    t.save()
    return HttpResponse("OK")


def add_task(request):
    if request.method == "POST":
        desc = request.POST["description"]
        t = TodoItem(description=desc)
        t.save()
    return redirect("tasks:list")


def delete_task(request, uid):
    t = TodoItem.objects.get(id=uid)
    t.delete()
    return redirect("tasks:list")


class TaskListView(ListView):
    queryset = TodoItem.objects.all()
    context_object_name = "tasks"
    template_name = "tasks/list.html"


class TaskCreateView(View):
    def post(self, request, *args, **kwargs):
        form = TodoItemForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("tasks:list")
        return render(request, "tasks/create.html", {"form": form})
    def get(self, request, *args, **kwargs):
        form = TodoItemForm()
        return render(request, "tasks/create.html", {"form": form})

class TaskDetailView(DetailView):
    model = TodoItem
    template_name = 'tasks/details.html'

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block title %}Войдите{% endblock %}

{% block main_content %}
<h1>Вход</h1>
<p>Введите логин/пароль:</p>
<form action="." method="post" class="login">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit">Войти</button>
</form>
{% endblock %}

tasks/templates/tasks/create.html
{% extends "base.html" %}
{% load static%}

{% block title%} Создать задачу {% endblock %}

{% block main_content %}
        <h1>Создать форму</h1>
        <form action="." method="post" class="row g-3 add-task">
            {% csrf_token %}
            <div class="col-auto myclass">
                {{ form }}
            </div>
            <div class="col-auto">
                <button class="add btn btn-primary mb-3" type="submit">Добавить</button>
            </div>
        </form>
{% endblock %}

tasks/templates/tasks/details.html
{% extends "base.html" %}
{% load static %}
{% block title %}Задача {{ object.id }}{% endblock %}
{% block extra_head %}
<link rel="stylesheet" 
      href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" 
      integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" 
      crossorigin="anonymous">
{% endblock %}

{% block main_content %}
<h1 style="padding: 10px 0; font-weight: bold;">Задача</h1>
<p><b>Описание</b>: {{ object }}</p>
<ul style="padding: 0px; font-weight: bold;">
    <li>
        {{ object.is_completed|yesno:"Выполнена,Не выполнена" }}
    </li>
    <li><i class="far fa-calendar-alt"></i>&nbsp;Создана: {{ object.created }}</li>
    <li><i class="far fa-clock"></i>&nbsp;Последнее изменене: {{object.update}} </li>
</ul>
<i class="fas fa-clipboard-list"></i>&nbsp;<a class="link_back_detals" href={% url 'tasks:list' %}>Назад к списку</a>
{% endblock %}

tasks/templates/tasks/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}Задачи на день{% endblock %}
{% block extra_head %}
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}
{% block main_content %}
<h1>Текущие задачи</h1>
<ul id="todo-list">
    {% for task in tasks %}
    {% if task.is_completed %}
    <li class="completed">
        <input class='checkbox' data-uid={{ task.id }} type='checkbox' disabled='disabled' checked='checked' />
        {% else %}
    <li>
        <input class='checkbox' data-uid={{ task.id }} type='checkbox' />
        {% endif %}
        <a class="name_tasks" href={% url "tasks:details" task.id %}>{{ task }}</a>
        <a class="remove" href={% url 'tasks:delete' task.id %}></a>
        <hr />
    </li>
    {% endfor %}
</ul>

<form action={% url 'tasks:create' %} class="row g-3 button-creat">
    <div class="col-auto">
        <button class="add btn btn-primary mb-3" type="submit">Добавить задачу</button>
    </div>
</form>
{% endblock %}

templates/base.html
{% load static %}
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Туду-дуду{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    
        <script src="http://code.jquery.com/jquery-3.6.0.min.js"></script>
        {% block extra_head %}
        {% endblock %}
    </head>
<body>
    <div class="container">
        {% block main_content %}
        {% endblock %}
    </div>
</body>
</html>